# Generated by Django 3.0.5 on 2021-02-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (0, 'unknown')], verbose_name='sex')),
                ('profession', models.CharField(max_length=128, verbose_name='profession')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('qq', models.CharField(max_length=128, verbose_name='QQ')),
                ('phone', models.CharField(max_length=11, verbose_name='telephone')),
                ('status', models.IntegerField(choices=[(0, 'apply'), (1, 'pass'), (2, 'refuse')], default=0, verbose_name='Audit State')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
            options={
                'verbose_name': 'student information',
                'verbose_name_plural': 'student information',
            },
        ),
    ]
