# Generated by Django 3.0.5 on 2021-02-10 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=128)),
                ('picture', models.ImageField(default='http://lorempixel.com/300/300/people/', upload_to='commodity_images')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity of commodity')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('departure', models.CharField(max_length=64)),
                ('numberOfComments', models.PositiveIntegerField(default=0, verbose_name='number of comments')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltfish.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'commodities',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default='http://lorempixel.com/300/300/people/', upload_to='profile_images')),
                ('phone', models.CharField(default='', max_length=32, verbose_name='telephone')),
                ('grade', models.PositiveIntegerField(choices=[(1, 'fresh man'), (2, 'sophomore'), (3, 'junior'), (4, 'senior')], default=1)),
                ('faculty', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='register time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user information',
                'verbose_name_plural': 'user information',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 'released'), (2, 'bought'), (3, 'sold'), (4, 'cart'), (5, 'collection')], default=1)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltfish.Commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'records',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(choices=[(1, 'To be delivered'), (2, 'To be received'), (3, 'To be evaluated'), (4, 'goods of rejected'), (5, 'completed')], default=3)),
                ('address', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('receipt_time', models.DateTimeField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltfish.Commodity')),
            ],
            options={
                'verbose_name_plural': 'orders',
            },
        ),
    ]
