# Generated by Django 3.0.5 on 2021-02-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltfish', '0002_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='numberOfComments',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
