# Generated by Django 3.0.5 on 2021-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltfish', '0003_auto_20210215_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='likes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='numberOfComments',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
