# Generated by Django 3.0.5 on 2021-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltfish', '0004_auto_20210215_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='numberOfComments',
            field=models.IntegerField(default=0, null=True, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='quantity',
            field=models.IntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
