# Generated by Django 3.0.5 on 2021-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltfish', '0005_auto_20210215_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'To be delivered'), (2, 'To be received'), (3, 'To be evaluated'), (4, 'goods of rejected'), (5, 'completed')], default=1),
        ),
    ]
