# Generated by Django 3.0.5 on 2021-02-16 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saltfish', '0006_auto_20210215_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='numberOfComments',
            field=models.IntegerField(default=0, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='receipt_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
