# Generated by Django 3.0.5 on 2021-02-16 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saltfish', '0008_comment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'unread'), (2, 'read')])),
                ('type', models.PositiveIntegerField(choices=[(1, 'bought_seller'), (2, 'bought_buyer'), (3, 'send_seller'), (4, 'send_buyer'), (5, 'receiver_seller'), (6, 'receiver_buyer')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saltfish.Commodity')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notices',
            },
        ),
    ]
